deal with system-dependent limit on the lengths of containers
Use the len method on the IP object, rather than calling the builtin len:
>>> from IPy import IP
>>> prefix = IP('0.0.0.0/1')
>>> len(prefix)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: long int too large to convert to int
>>> prefix.len()
2147483648L
>>>